//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceClient.CheckoutServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ordertype", Namespace="http://schemas.datacontract.org/2004/07/NewCommerceService")]
    [System.SerializableAttribute()]
    public partial class Ordertype : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApprovedStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SumPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SumQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApprovedStatus {
            get {
                return this.ApprovedStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovedStatusField, value) != true)) {
                    this.ApprovedStatusField = value;
                    this.RaisePropertyChanged("ApprovedStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SumPrice {
            get {
                return this.SumPriceField;
            }
            set {
                if ((this.SumPriceField.Equals(value) != true)) {
                    this.SumPriceField = value;
                    this.RaisePropertyChanged("SumPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SumQuantity {
            get {
                return this.SumQuantityField;
            }
            set {
                if ((this.SumQuantityField.Equals(value) != true)) {
                    this.SumQuantityField = value;
                    this.RaisePropertyChanged("SumQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinalOrdertype", Namespace="http://schemas.datacontract.org/2004/07/NewCommerceService")]
    [System.SerializableAttribute()]
    public partial class FinalOrdertype : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinalOrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ShippingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SumPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SumQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinalOrderID {
            get {
                return this.FinalOrderIDField;
            }
            set {
                if ((this.FinalOrderIDField.Equals(value) != true)) {
                    this.FinalOrderIDField = value;
                    this.RaisePropertyChanged("FinalOrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShippingDate {
            get {
                return this.ShippingDateField;
            }
            set {
                if ((this.ShippingDateField.Equals(value) != true)) {
                    this.ShippingDateField = value;
                    this.RaisePropertyChanged("ShippingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SumPrice {
            get {
                return this.SumPriceField;
            }
            set {
                if ((this.SumPriceField.Equals(value) != true)) {
                    this.SumPriceField = value;
                    this.RaisePropertyChanged("SumPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SumQuantity {
            get {
                return this.SumQuantityField;
            }
            set {
                if ((this.SumQuantityField.Equals(value) != true)) {
                    this.SumQuantityField = value;
                    this.RaisePropertyChanged("SumQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CheckoutServiceReference.IServiceCheckout")]
    public interface IServiceCheckout {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCheckout/ProceedTOCheckout", ReplyAction="http://tempuri.org/IServiceCheckout/ProceedTOCheckoutResponse")]
        CommerceClient.CheckoutServiceReference.Ordertype[] ProceedTOCheckout(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCheckout/ProceedTOCheckout", ReplyAction="http://tempuri.org/IServiceCheckout/ProceedTOCheckoutResponse")]
        System.Threading.Tasks.Task<CommerceClient.CheckoutServiceReference.Ordertype[]> ProceedTOCheckoutAsync(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCheckout/DisplayOrder", ReplyAction="http://tempuri.org/IServiceCheckout/DisplayOrderResponse")]
        CommerceClient.CheckoutServiceReference.Ordertype[] DisplayOrder(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCheckout/DisplayOrder", ReplyAction="http://tempuri.org/IServiceCheckout/DisplayOrderResponse")]
        System.Threading.Tasks.Task<CommerceClient.CheckoutServiceReference.Ordertype[]> DisplayOrderAsync(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCheckout/FinalBuy", ReplyAction="http://tempuri.org/IServiceCheckout/FinalBuyResponse")]
        CommerceClient.CheckoutServiceReference.FinalOrdertype[] FinalBuy(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCheckout/FinalBuy", ReplyAction="http://tempuri.org/IServiceCheckout/FinalBuyResponse")]
        System.Threading.Tasks.Task<CommerceClient.CheckoutServiceReference.FinalOrdertype[]> FinalBuyAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCheckout/getOrder", ReplyAction="http://tempuri.org/IServiceCheckout/getOrderResponse")]
        CommerceClient.CheckoutServiceReference.Ordertype getOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCheckout/getOrder", ReplyAction="http://tempuri.org/IServiceCheckout/getOrderResponse")]
        System.Threading.Tasks.Task<CommerceClient.CheckoutServiceReference.Ordertype> getOrderAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCheckout/deleteOrder", ReplyAction="http://tempuri.org/IServiceCheckout/deleteOrderResponse")]
        bool deleteOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCheckout/deleteOrder", ReplyAction="http://tempuri.org/IServiceCheckout/deleteOrderResponse")]
        System.Threading.Tasks.Task<bool> deleteOrderAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCheckoutChannel : CommerceClient.CheckoutServiceReference.IServiceCheckout, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCheckoutClient : System.ServiceModel.ClientBase<CommerceClient.CheckoutServiceReference.IServiceCheckout>, CommerceClient.CheckoutServiceReference.IServiceCheckout {
        
        public ServiceCheckoutClient() {
        }
        
        public ServiceCheckoutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCheckoutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCheckoutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCheckoutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CommerceClient.CheckoutServiceReference.Ordertype[] ProceedTOCheckout(string Username) {
            return base.Channel.ProceedTOCheckout(Username);
        }
        
        public System.Threading.Tasks.Task<CommerceClient.CheckoutServiceReference.Ordertype[]> ProceedTOCheckoutAsync(string Username) {
            return base.Channel.ProceedTOCheckoutAsync(Username);
        }
        
        public CommerceClient.CheckoutServiceReference.Ordertype[] DisplayOrder(string Username) {
            return base.Channel.DisplayOrder(Username);
        }
        
        public System.Threading.Tasks.Task<CommerceClient.CheckoutServiceReference.Ordertype[]> DisplayOrderAsync(string Username) {
            return base.Channel.DisplayOrderAsync(Username);
        }
        
        public CommerceClient.CheckoutServiceReference.FinalOrdertype[] FinalBuy(int id) {
            return base.Channel.FinalBuy(id);
        }
        
        public System.Threading.Tasks.Task<CommerceClient.CheckoutServiceReference.FinalOrdertype[]> FinalBuyAsync(int id) {
            return base.Channel.FinalBuyAsync(id);
        }
        
        public CommerceClient.CheckoutServiceReference.Ordertype getOrder(int id) {
            return base.Channel.getOrder(id);
        }
        
        public System.Threading.Tasks.Task<CommerceClient.CheckoutServiceReference.Ordertype> getOrderAsync(int id) {
            return base.Channel.getOrderAsync(id);
        }
        
        public bool deleteOrder(int id) {
            return base.Channel.deleteOrder(id);
        }
        
        public System.Threading.Tasks.Task<bool> deleteOrderAsync(int id) {
            return base.Channel.deleteOrderAsync(id);
        }
    }
}
